version: '3'

services:
  openconnect:
    image: anchiru/openconnect-client:latest
    container_name: openconnect-client
    env_file: .env
    network_mode: "host"
    privileged: true
    restart: unless-stopped
